[book]
authors = ["Toshiyuki Yoshida"]
language = "ja"
src = "src"
title = "生成AI利用ガイドライン チェックリスト v1.0.0-rc.1"

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = ""

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "[[TOC]]"
